language: rust
sudo: false
cache: cargo

# kcov dependencies (coverage)
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - zlib1g-dev 
      - libiberty-dev 
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

# Test the trains
rust:
  - stable
  - beta
  - nightly

# Allowed failures on non-stable trains
matrix:
  allow_failures:
    - rust: beta
    - rust: nightly

# Load travis-cargo
before_script:
  - cargo install cargo-travis; export PATH=$HOME/.cargo/bin:$PATH

# Document, measure code coverage, upload to coveralls.io
after_success:
  - cargo doc
  - cargo coveralls

# Disable build notifications
notifications:
  email: false