language: rust
sudo: false
cache: cargo

# kcov dependencies (coverage)
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

rust:
  - stable
  - beta
  - nightly

# whitelist
branches:
  only:
    - master
    - develop
    - /^release/.*$/

matrix:
  allow_failures:
    - rust: beta
    - rust: nightly

# Load travis-cargo
before_script:
  - |
      cargo install cargo-travis --force &&
      export PATH=$HOME/.cargo/bin:$PATH

jobs:
  include:
    - stage: doc
      script: cargo doc
      rust: stable

# Measure code coverage, upload to coveralls.io
after_success:
  - cargo coveralls