[package]
authors = ["James Zhu <jameszhu@berkeley.edu>"]
name = "telescope"
version = "0.4.0"

[dependencies]
combine = "2.3.0"
error-chain = "0.10.0"
float-cmp = "0.2.3"
itertools = "0.6.0"
quickcheck = "0.4.1"
rustyline = "1.0.0"
unicode-xid = "0.1.0"
