[package]
name = "telescope"
version = "0.3.0"
authors = ["James Zhu <james.zhu.engineer@gmail.com>"]

[dependencies]
rustyline = "1.0"
error-chain = "0.10"
quickcheck = "0.4"
combine = "2.0.0"

[[bin]]
name = "tele"
