[package]
name = "telescope"
version = "0.2.0"
authors = ["James Zhu <james.zhu.engineer@gmail.com>"]

[dependencies]
rustyline = "1.0.0"
error-chain = "0.8.0"
quickcheck = "0.4.0"
combine = "2.0.0"

[[bin]]
name = "tele"
