[package]
name = "lrs"
version = "0.2.0"
authors = ["James Zhu <james.zhu.engineer@gmail.com>"]
build = "build.rs"

[build-dependencies]
lalrpop = "0.12.0"

[dependencies]
lalrpop-util = "0.12.0"
rustyline = "0.2.3"
error-chain = "0.5.0"

[[bin]]
name = "lrs"
