[package]
name = "telescope"
version = "0.4.0"
authors = ["James Zhu <james.zhu.engineer@gmail.com>"]

[dependencies]
combine = "2.3.0"
rustyline = "1.0.0"
error-chain = "0.10.0"

# [dev-dependencies]
float-cmp = "0.2.3"
quickcheck = "0.4.1"